name: Deploying multiple Lambdas

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the `main` branch

jobs:
  deploy-lambdas:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu

    strategy:
      matrix:
        lambda: [lambda1, lambda2]  # List of Lambda directories you want to deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checkout the code from your repository

      - name: Set up Node.js environment
        uses: actions/setup-node@v3  # Set up the Node.js environment
        with:
          node-version: '20'  # Specify Node.js version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3  # Set up AWS credentials
        with:
          aws-access-key-id: ${{ secrets.AKIAQ4J5X2RZLEUBV54P }}  # Use GitHub secrets for AWS credentials
          aws-secret-access-key: ${{ secrets.aWn6aHhqE7CkjkCg2rXCA5pFuxc7UVZjifW9v71U }}
          aws-region: us-east-1  # Specify the AWS region (adjust if needed)

      - name: Zip the Lambda function
        run: zip -r ${{ matrix.lambda }}.zip ./${{ matrix.lambda }}/index.js  # Zip the Lambda code

      - name: Deploy the Lambda function
        run: aws lambda update-function-code --function-name=${{ matrix.lambda }} --zip-file fileb://${{ matrix.lambda }}.zip  # Deploy Lambda to AWS
